### ISSUE TITLE
Thank you very much for the excellent AB test simulator.

### ISSUE THREAD

**Issue by V-Boldyreff** [lukasvermeer/confidence#10]
Good day Lucas.
Thank you very much for the excellent AB test simulator.
https://www.lukasvermeer.nl/confidence/index.html
This is really cool stuff.
Can I ask you to watch it when you have a free minute?
In my opinion it stopped working properly.
![image](https://user-images.githubusercontent.com/91187010/203360042-dee44480-a11b-4e17-ab58-4191c534e4c0.png)

**Comment by lukasvermeer** [comment]
Thanks for reporting @V-Boldyreff! Looks like some breaking changes were introduced in Vuefire. I will fix to the latest version before these changes were introduced.
