### ISSUE TITLE
What is the License? Can I reuse something?

### ISSUE THREAD

**Issue by mysticaltech** [lukasvermeer/confidence#9]
Hello @lukasvermeer, first of all, thank you for your amazing work (I'm a big fan). I want to reuse a small part of this, specifically, the confidence interval SVG, is this MIT licensed, it's not mentioned so I prefer to ask you. Would that be ok?
![Screen Shot 2021-04-08 at 6 39 19 PM](https://user-images.githubusercontent.com/518555/114064296-c6f07e00-9899-11eb-8dc3-21ce80b2ab09.png)

**Comment by lukasvermeer** [comment]
Currently it's not MIT licensed. I'd have to think about what licence I should use. I honestly wasn't expecting anyone to want to reuse anything from this pet project.

What do you want to use the SVG for?

**Comment by mysticaltech** [comment]
Ok, I understand, sorry to have put you in a corner like this. I'm building an A/B testing reporting tool and thought this was interesting. But it's ok, I'll just be using this nice library VisX from AirBnB that provides a react component for Box Plots [https://airbnb.io/visx/docs/stats](https://airbnb.io/visx/docs/stats).

Cheers, and keep up the good work!

**Comment by lukasvermeer** [comment]
Don't apologise! Entirely my fault! I just never considered the possibility that anyone would want to reuse this work. 😅

VisX looks nice. Probably a better choice than using my code. 😬
